//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit 的本地化字符串。
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New a Preset 的本地化字符串。
        /// </summary>
        public static string MenuItem_Edit_NewPreset {
            get {
                return ResourceManager.GetString("MenuItem_Edit_NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open a Preset 的本地化字符串。
        /// </summary>
        public static string MenuItem_Edit_OpenPreset {
            get {
                return ResourceManager.GetString("MenuItem_Edit_OpenPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Preset 的本地化字符串。
        /// </summary>
        public static string MenuItem_Edit_SaveAsPreset {
            get {
                return ResourceManager.GetString("MenuItem_Edit_SaveAsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save the Preset 的本地化字符串。
        /// </summary>
        public static string MenuItem_Edit_SavePreset {
            get {
                return ResourceManager.GetString("MenuItem_Edit_SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File(s) 的本地化字符串。
        /// </summary>
        public static string MenuItem_File_SelectFile {
            get {
                return ResourceManager.GetString("MenuItem_File_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder(s) 的本地化字符串。
        /// </summary>
        public static string MenuItem_File_SelectFolder {
            get {
                return ResourceManager.GetString("MenuItem_File_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Setting 的本地化字符串。
        /// </summary>
        public static string Menultem_Setting {
            get {
                return ResourceManager.GetString("Menultem_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files Renamer 的本地化字符串。
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
